app = "gmpi-backend"
primary_region = "par"

[build]

[env]
  SECRET_KEY = "changez_cette_clé_secrète_jwt_très_longue_et_sécurisée_pour_production"
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  CORS_ORIGINS = "https://votre-frontend.vercel.app"

[http_service]
  internal_port = 8000
  force_https = true

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/docs"
