[phases.setup]
nixPkgs = ['nodejs', 'python39']

[phases.install]
cmds = ['npm install --prefix frontend', 'pip install -r requirements.txt']

[phases.build]
cmds = ['npm run build --prefix frontend']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'

